name: capstone
channels:
  - conda-forge
  - defaults
dependencies:
  - _openmp_mutex=4.5
  - aiohappyeyeballs=2.6.1
  - aiohttp=3.13.2
  - aiosignal=1.4.0
  - aom=3.9.1
  - attrs=25.4.0
  - backports.zstd=1.2.0
  - blosc=1.21.6
  - brotli=1.2.0
  - brotli-bin=1.2.0
  - brotli-python=1.2.0
  - bzip2=1.0.8
  - ca-certificates=2025.11.12
  - cairo=1.18.4
  - certifi=2025.11.12
  - charset-normalizer=3.4.4
  - cli11=2.6.0
  - colorama=0.4.6
  - contourpy=1.3.3
  - cycler=0.12.1
  - dav1d=1.2.1
  - double-conversion=3.3.1
  - ffmpeg=8.0.1
  - fmt=12.0.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.61.1
  - freetype=2.14.1
  - fribidi=1.0.16
  - frozenlist=1.7.0
  - gdk-pixbuf=2.44.4
  - gl2ps=1.4.2
  - glslang=16.1.0
  - graphite2=1.3.14
  - h2=4.3.0
  - harfbuzz=12.2.0
  - hdf4=4.2.15
  - hdf5=1.14.6
  - hpack=4.1.0
  - hyperframe=6.1.0
  - icu=75.1
  - idna=3.11
  - jsoncpp=1.9.6
  - kiwisolver=1.4.9
  - krb5=1.21.3
  - lame=3.100
  - lcms2=2.17
  - lerc=4.0.0
  - libaec=1.1.4
  - libblas=3.11.0
  - libbrotlicommon=1.2.0
  - libbrotlidec=1.2.0
  - libbrotlienc=1.2.0
  - libcblas=3.11.0
  - libclang13=21.1.7
  - libcurl=8.17.0
  - libdeflate=1.25
  - libexpat=2.7.3
  - libffi=3.5.2
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgcc=15.2.0
  - libglib=2.86.2
  - libgomp=15.2.0
  - libhwloc=2.12.1
  - libiconv=1.18
  - libintl=0.22.5
  - libjpeg-turbo=3.1.2
  - liblapack=3.11.0
  - liblzma=5.8.1
  - libmpdec=4.0.0
  - libnetcdf=4.9.3
  - libogg=1.3.5
  - libopus=1.6
  - libpng=1.6.53
  - librsvg=2.60.0
  - libsqlite=3.51.1
  - libssh2=1.11.1
  - libtheora=1.1.1
  - libtiff=4.7.1
  - libusb=1.0.29
  - libvorbis=1.3.7
  - libvulkan-loader=1.4.328.1
  - libwebp-base=1.6.0
  - libwinpthread=12.0.0.r4.gg4f2fc60ca
  - libxcb=1.17.0
  - libxml2=2.15.1
  - libxml2-16=2.15.1
  - libxslt=1.1.43
  - libzip=1.11.2
  - libzlib=1.3.1
  - llvm-openmp=21.1.7
  - loguru=0.7.3
  - lz4-c=1.10.0
  - matplotlib=3.10.8
  - matplotlib-base=3.10.8
  - mkl=2025.3.0
  - msgpack-python=1.1.2
  - multidict=6.7.0
  - munkres=1.1.4
  - nlohmann_json=3.12.0
  - numpy=2.3.5
  - openh264=2.6.0
  - openjpeg=2.5.4
  - openssl=3.6.0
  - packaging=25.0
  - pango=1.56.4
  - pcre2=10.46
  - pillow=12.0.0
  - pip=25.3
  - pixman=0.46.4
  - platformdirs=4.5.1
  - pooch=1.8.2
  - proj=9.7.1
  - propcache=0.3.1
  - pthread-stubs=0.4
  - pugixml=1.15
  - pyparsing=3.2.5
  - pyside6=6.9.3
  - pysocks=1.7.1
  - python=3.13.11
  - python-dateutil=2.9.0.post0
  - python_abi=3.13
  - pyvista=0.46.4
  - qhull=2020.2
  - qt6-main=6.9.3
  - requests=2.32.5
  - scooby=0.11.0
  - sdl2=2.32.56
  - sdl3=3.2.28
  - shaderc=2025.5
  - six=1.17.0
  - snappy=1.2.2
  - spirv-tools=2025.4
  - sqlite=3.51.1
  - svt-av1=3.1.2
  - tbb=2022.3.0
  - tk=8.6.13
  - tornado=6.5.4
  - typing-extensions=4.15.0
  - typing_extensions=4.15.0
  - tzdata=2025c
  - ucrt=10.0.26100.0
  - urllib3=2.6.2
  - utfcpp=4.0.8
  - vc=14.3
  - vc14_runtime=14.44.35208
  - vcomp14=14.44.35208
  - vs2015_runtime=14.44.35208
  - vtk-base=9.5.2
  - win32_setctime=1.2.0
  - win_inet_pton=1.1.0
  - wslink=2.5.0
  - x264=1!164.3095
  - x265=3.5
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - yarl=1.22.0
  - zlib=1.3.1
  - zlib-ng=2.3.2
  - zstd=1.5.7
  - pip:
      - future==1.0.0
      - iso8601==2.1.0
      - pyserial==3.5
      - pyyaml==6.0.3
prefix: C:\Users\aadis\anaconda3\envs\capstone
